# Site settings
title: 3tgame find my shadow
email: 3tgame@domain.com
description: > # this means to ignore newlines until "baseurl:"
  一直在寻找，下个路口会遇见谁。望着天上的月亮，有种我走它走的错觉。时间告诉我，它不会等我。
  望着天上星星，看似很近、实际很远。
baseurl: "/myblog/" # the subpath of your site, e.g. /blog/
url: "http://tgname.tk" # the base hostname & protocol for your site
twitter_username: tgnian
github_username:  3tgame

# Build settings
markdown: kramdown
